### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by shreevardhan97** [Deep911/webCamEmocognizer#8]
Traceback (most recent call last):
  File "./genScaledDat.py", line 15, in <module>
    np.save('WebcamFacialExpressionRecognizer/data/Scaled.bin.npy',data)
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/numpy/lib/npyio.py", line 517, in save
    fid = open(file, "wb")
IOError: [Errno 2] No such file or directory: 'WebcamFacialExpressionRecognizer/data/Scaled.bin.npy'

How to fix this?

**Comment by shreevardhan97** [comment]
Just had to change path in the genScaledDat.py file.
