### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by shreevardhan97** [Deep911/webCamEmocognizer#9]
Using TensorFlow backend.
Traceback (most recent call last):
  File "./trainCNN.py", line 4, in <module>
    from keras.datasets import mnist
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/shreevardhanshah/Library/Python/2.7/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

**Comment by shreevardhan97** [comment]
Used tensor flow 1.5 to fix this issue 
pip install tensorflow==1.5
